 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '--tag', 'us.gcr.io/$PROJECT_ID/thermostat-agent:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'us.gcr.io/$PROJECT_ID/thermostat-agent:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'thermostat-agent'
   - '--image'
   - 'us.gcr.io/$PROJECT_ID/thermostat-agent:$COMMIT_SHA'
   - '--region'
   - 'us-east4'
   - '--platform'
   - 'managed'
 images:
 - 'us.gcr.io/$PROJECT_ID/thermostat-agent:$COMMIT_SHA'